apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    prelusion.wildsea.service: hapi-fhir-server
  name: hapi-fhir-server
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32069
  selector:
    prelusion.wildsea.service: hapi-fhir-server
status:
  loadBalancer: {}
