apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    prelusion.wildsea.service: hapi-fhir-server
  name: hapi-fhir-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      prelusion.wildsea.service: hapi-fhir-server
  template:
    metadata:
      labels:
        prelusion.wildsea.service: hapi-fhir-server
    spec:
      containers:
        - image: prelusion/wild-sea-hapi-fhir:latest # This is for docker-hub
          # - image: registry.digitalocean.com/wildsea-fhir/wildsea-hapi-fhir:latest #Digital Ocean Registry image
          name: hapi-fhir-server
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
