apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    prelusion.wildsea.service: hapi-fhir-mysql
  name: hapi-fhir-mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    prelusion.wildsea.service: hapi-fhir-mysql
status:
  loadBalancer: {}
